[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Texamples-tulip/linker.ld",
    "-C", "link-arg=--no-pie",
    "-C", "relocation-model=static",
]
