//! Raw C bindings generated by bindgen from Microsoft mu_msvm headers.
//!
//! These are wire-format structs for the NVSP, RNDIS, and VMBus protocols.
//! Source: microsoft/mu_msvm (BSD-2-Clause-Patent)
//! See `include/README.md` for header provenance.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::too_many_arguments,
    clippy::useless_transmute,
    clippy::missing_safety_doc,
    clippy::fn_to_numeric_cast,
    clippy::ptr_offset_with_cast,
    clippy::unnecessary_cast
)]

include!(concat!(env!("OUT_DIR"), "/hyperv_bindings.rs"));

// ── Constant aliases (mu_msvm PascalCase → Linux UPPER_SNAKE_CASE) ──────

// NVSP message types
pub const NVSP_MSG_TYPE_NONE: u32 = NvspMessageTypeNone;
pub const NVSP_MSG_TYPE_INIT: u32 = NvspMessageTypeInit;
pub const NVSP_MSG_TYPE_INIT_COMPLETE: u32 = NvspMessageTypeInitComplete;
pub const NVSP_MSG1_TYPE_SEND_NDIS_VER: u32 = NvspMessage1TypeSendNdisVersion;
pub const NVSP_MSG1_TYPE_SEND_RECV_BUF: u32 = NvspMessage1TypeSendReceiveBuffer;
pub const NVSP_MSG1_TYPE_SEND_RECV_BUF_COMPLETE: u32 = NvspMessage1TypeSendReceiveBufferComplete;
pub const NVSP_MSG1_TYPE_REVOKE_RECV_BUF: u32 = NvspMessage1TypeRevokeReceiveBuffer;
pub const NVSP_MSG1_TYPE_SEND_SEND_BUF: u32 = NvspMessage1TypeSendSendBuffer;
pub const NVSP_MSG1_TYPE_SEND_SEND_BUF_COMPLETE: u32 = NvspMessage1TypeSendSendBufferComplete;
pub const NVSP_MSG1_TYPE_REVOKE_SEND_BUF: u32 = NvspMessage1TypeRevokeSendBuffer;
pub const NVSP_MSG1_TYPE_SEND_RNDIS_PKT: u32 = NvspMessage1TypeSendRNDISPacket;
pub const NVSP_MSG1_TYPE_SEND_RNDIS_PKT_COMPLETE: u32 = NvspMessage1TypeSendRNDISPacketComplete;
pub const NVSP_MSG2_TYPE_SEND_NDIS_CONFIG: u32 = NvspMessage2TypeSendNdisConfig;
pub const NVSP_MSG4_TYPE_SEND_VF_ASSOCIATION: u32 = NvspMessage4TypeSendVFAssociation;
pub const NVSP_MSG4_TYPE_SWITCH_DATA_PATH: u32 = NvspMessage4TypeSwitchDataPath;
pub const NVSP_MSG5_TYPE_SUBCHANNEL: u32 = NvspMessage5TypeSubChannel;
pub const NVSP_MSG5_TYPE_SEND_INDIRECTION_TABLE: u32 = NvspMessage5TypeSendIndirectionTable;

// NVSP status
pub const NVSP_STAT_NONE: u32 = NvspStatusNone;
pub const NVSP_STAT_SUCCESS: u32 = NvspStatusSuccess;
pub const NVSP_STAT_FAIL: u32 = NvspStatusFailure;
pub const NVSP_STAT_PROTOCOL_TOO_NEW: u32 = NvspStatusDeprecated1;
pub const NVSP_STAT_PROTOCOL_TOO_OLD: u32 = NvspStatusDeprecated2;
pub const NVSP_STAT_INVALID_RNDIS_PKT: u32 = NvspStatusInvalidRndisPacket;
pub const NVSP_STAT_BUSY: u32 = NvspStatusBusy;
pub const NVSP_STAT_PROTOCOL_UNSUPPORTED: u32 = NvspStatusProtocolVersionUnsupported;

// NVSP protocol versions (from NVSP_PROTOCOL_VERSION macro, not expandable by bindgen)
pub const NVSP_PROTOCOL_VERSION_1: u32 = 0x00002; // NVSP_PROTOCOL_VERSION(0,2)
pub const NVSP_PROTOCOL_VERSION_2: u32 = 0x30002; // NVSP_PROTOCOL_VERSION(3,2)
pub const NVSP_PROTOCOL_VERSION_4: u32 = 0x40000; // NVSP_PROTOCOL_VERSION(4,0)
pub const NVSP_PROTOCOL_VERSION_5: u32 = 0x50000; // NVSP_PROTOCOL_VERSION(5,0)
pub const NVSP_PROTOCOL_VERSION_6: u32 = 0x60000; // NVSP_PROTOCOL_VERSION(6,0)
pub const NVSP_PROTOCOL_VERSION_61: u32 = 0x60001; // NVSP_PROTOCOL_VERSION(6,1)

// VMBus packet types
pub const VM_PKT_DATA_INBAND: u32 = VmbusPacketTypeDataInBand;
pub const VM_PKT_DATA_USING_XFER_PAGES: u32 = VmbusPacketTypeDataUsingTransferPages;
pub const VM_PKT_DATA_USING_GPA_DIRECT: u32 = VmbusPacketTypeDataUsingGpaDirect;
pub const VM_PKT_COMP: u32 = VmbusPacketTypeCompletion;

// RNDIS message types (from rndis_msvm.h REMOTE_NDIS_* constants)
pub const RNDIS_MSG_COMPLETION: u32 = 0x80000000;
pub const RNDIS_MSG_PACKET: u32 = REMOTE_NDIS_PACKET_MSG;
pub const RNDIS_MSG_INIT: u32 = REMOTE_NDIS_INITIALIZE_MSG;
pub const RNDIS_MSG_INIT_C: u32 = REMOTE_NDIS_INITIALIZE_CMPLT;
pub const RNDIS_MSG_HALT: u32 = REMOTE_NDIS_HALT_MSG;
pub const RNDIS_MSG_QUERY: u32 = REMOTE_NDIS_QUERY_MSG;
pub const RNDIS_MSG_QUERY_C: u32 = REMOTE_NDIS_QUERY_CMPLT;
pub const RNDIS_MSG_SET: u32 = REMOTE_NDIS_SET_MSG;
pub const RNDIS_MSG_SET_C: u32 = REMOTE_NDIS_SET_CMPLT;
pub const RNDIS_MSG_RESET: u32 = REMOTE_NDIS_RESET_MSG;
pub const RNDIS_MSG_RESET_C: u32 = REMOTE_NDIS_RESET_MSG | RNDIS_MSG_COMPLETION;
pub const RNDIS_MSG_INDICATE: u32 = REMOTE_NDIS_INDICATE_STATUS_MSG;
pub const RNDIS_MSG_KEEPALIVE: u32 = REMOTE_NDIS_KEEPALIVE_MSG;
pub const RNDIS_MSG_KEEPALIVE_C: u32 = REMOTE_NDIS_KEEPALIVE_MSG | RNDIS_MSG_COMPLETION;

// NDIS packet filter flags (not in mu_msvm rndis.h, defined per NDIS spec)
pub const NDIS_PACKET_TYPE_DIRECTED: u32 = 0x00000001;
pub const NDIS_PACKET_TYPE_MULTICAST: u32 = 0x00000002;
pub const NDIS_PACKET_TYPE_ALL_MULTICAST: u32 = 0x00000004;
pub const NDIS_PACKET_TYPE_BROADCAST: u32 = 0x00000008;
pub const NDIS_PACKET_TYPE_PROMISCUOUS: u32 = 0x00000020;
pub const OID_GEN_SUPPORTED_LIST: u32 = 0x00010101;
pub const OID_GEN_HARDWARE_STATUS: u32 = 0x00010102;
pub const OID_GEN_MAXIMUM_FRAME_SIZE: u32 = 0x00010106;
pub const OID_GEN_LINK_SPEED: u32 = 0x00010107;
pub const OID_GEN_CURRENT_PACKET_FILTER: u32 = RNDIS_OID_GEN_CURRENT_PACKET_FILTER;
pub const OID_GEN_CURRENT_LOOKAHEAD: u32 = 0x0001010F;
pub const OID_GEN_MAXIMUM_TOTAL_SIZE: u32 = 0x00010111;
pub const OID_GEN_MEDIA_CONNECT_STATUS: u32 = 0x00010114;
pub const OID_GEN_RECEIVE_SCALE_CAPABILITIES: u32 = 0x00010203;
pub const OID_GEN_RECEIVE_SCALE_PARAMETERS: u32 = 0x00010204;
pub const OID_802_3_PERMANENT_ADDRESS: u32 = 0x01010101;
pub const OID_802_3_CURRENT_ADDRESS: u32 = RNDIS_OID_802_3_CURRENT_ADDRESS;
pub const OID_802_3_MAXIMUM_LIST_SIZE: u32 = 0x01010104;
pub const OID_802_3_MULTICAST_LIST: u32 = 0x01010103;
pub const OID_TCP_OFFLOAD_PARAMETERS: u32 = 0xFC01020C;
pub const OID_TCP_OFFLOAD_HARDWARE_CAPABILITIES: u32 = 0xFC01020D;

// NDIS packet filter flags (from rndis_msvm.h)
// (same values, already exported by bindgen)

// RNDIS status codes (mu_msvm uses RNDIS_STATUS as a typedef, values defined in rndis.h)
pub const RNDIS_STATUS_SUCCESS: u32 = 0x00000000;
pub const RNDIS_STATUS_PENDING: u32 = 0x00000103;
pub const RNDIS_STATUS_MEDIA_CONNECT: u32 = 0x4001000B;
pub const RNDIS_STATUS_MEDIA_DISCONNECT: u32 = 0x4001000C;
pub const RNDIS_STATUS_NETWORK_CHANGE: u32 = 0x40010018;
pub const RNDIS_STATUS_FAILURE: u32 = 0xC0000001;
pub const RNDIS_STATUS_NOT_SUPPORTED: u32 = 0xC00000BB;
pub const RNDIS_STATUS_RESOURCES: u32 = 0xC000009A;
pub const RNDIS_STATUS_INVALID_DATA: u32 = 0xC0010015;

// Buffer/section constants (not in mu_msvm, defined here)
pub const NETVSC_RECEIVE_BUFFER_ID: u32 = 0xcafe;
pub const NETVSC_SEND_BUFFER_ID: u32 = 0;
pub const NETVSC_RECEIVE_BUFFER_DEFAULT: u32 = 1024 * 1024 * 16;
pub const NETVSC_SEND_BUFFER_DEFAULT: u32 = 1024 * 1024;
pub const NETVSC_SEND_SECTION_SIZE: u32 = 6144;
pub const NETVSC_RECV_SECTION_SIZE: u32 = 1728;
pub const RNDIS_MAX_PKT_DEFAULT: u32 = 8;
pub const RNDIS_PKT_ALIGN_DEFAULT: u32 = 8;

// NVSP message types
pub type nvsp_message = NVSP_MESSAGE;
pub type nvsp_message_header = NVSP_MESSAGE_HEADER;
pub type nvsp_message_init = NVSP_MESSAGE_INIT;
pub type nvsp_message_init_complete = NVSP_MESSAGE_INIT_COMPLETE;
pub type nvsp_1_message_send_ndis_version = NVSP_1_MESSAGE_SEND_NDIS_VERSION;
pub type nvsp_1_message_send_receive_buffer = NVSP_1_MESSAGE_SEND_RECEIVE_BUFFER;
pub type nvsp_1_receive_buffer_section = NVSP_1_RECEIVE_BUFFER_SECTION;
pub type nvsp_1_message_send_receive_buffer_complete = NVSP_1_MESSAGE_SEND_RECEIVE_BUFFER_COMPLETE;
pub type nvsp_1_message_revoke_receive_buffer = NVSP_1_MESSAGE_REVOKE_RECEIVE_BUFFER;
pub type nvsp_1_message_send_send_buffer = NVSP_1_MESSAGE_SEND_SEND_BUFFER;
pub type nvsp_1_message_send_send_buffer_complete = NVSP_1_MESSAGE_SEND_SEND_BUFFER_COMPLETE;
pub type nvsp_1_message_revoke_send_buffer = NVSP_1_MESSAGE_REVOKE_SEND_BUFFER;
pub type nvsp_1_message_send_rndis_packet = NVSP_1_MESSAGE_SEND_RNDIS_PACKET;
pub type nvsp_1_message_send_rndis_packet_complete = NVSP_1_MESSAGE_SEND_RNDIS_PACKET_COMPLETE;
pub type nvsp_2_send_ndis_config = NVSP_2_MESSAGE_SEND_NDIS_CONFIG;
pub type nvsp_2_vsc_capability = NVSP_2_NETVSC_CAPABILITIES;

// RNDIS types
pub type rndis_message = RNDIS_MESSAGE;
pub type rndis_packet = RNDIS_PACKET;
pub type rndis_initialize_request = RNDIS_INITIALIZE_REQUEST;
pub type rndis_initialize_complete = RNDIS_INITIALIZE_COMPLETE;
pub type rndis_halt_request = RNDIS_HALT_REQUEST;
pub type rndis_query_request = RNDIS_QUERY_REQUEST;
pub type rndis_query_complete = RNDIS_QUERY_COMPLETE;
pub type rndis_set_request = RNDIS_SET_REQUEST;
pub type rndis_set_complete = RNDIS_SET_COMPLETE;
pub type rndis_reset_request = RNDIS_RESET_REQUEST;
pub type rndis_reset_complete = RNDIS_RESET_COMPLETE;
pub type rndis_indicate_status = RNDIS_INDICATE_STATUS;
pub type rndis_keepalive_request = RNDIS_KEEPALIVE_REQUEST;
pub type rndis_keepalive_complete = RNDIS_KEEPALIVE_COMPLETE;

// VMBus packet types
pub type vmpacket_descriptor = VMPACKET_DESCRIPTOR;
pub type vmtransfer_page_range = VMTRANSFER_PAGE_RANGE;
pub type vmtransfer_page_packet_header = VMTRANSFER_PAGE_PACKET_HEADER;
