//! Raw C bindings generated by bindgen from the Hyper-V Linux kernel headers.
//!
//! These are wire-format structs for the NVSP, RNDIS, and VMBus protocols.
//! See `include/README.md` for header provenance.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::too_many_arguments,
    clippy::useless_transmute,
    clippy::missing_safety_doc,
    clippy::fn_to_numeric_cast,
    clippy::ptr_offset_with_cast
)]

include!(concat!(env!("OUT_DIR"), "/hyperv_bindings.rs"));
